import './style.css';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TYPES,generateLayout,validProject} from './model.js';
const $=id=>document.getElementById(id), viewport=$('viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#10191f');scene.fog=new THREE.Fog('#10191f',35,95);
const camera=new THREE.PerspectiveCamera(40,1,.1,200);camera.position.set(17,14,20);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;viewport.prepend(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.48;controls.target.set(4,1,3);
scene.add(new THREE.HemisphereLight(0xb1d9ed,0x363a31,2));const sun=new THREE.DirectionalLight(0xffefca,3);sun.position.set(10,20,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30});scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:'#17242c',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.06;ground.receiveShadow=true;scene.add(ground);
const grid=new THREE.GridHelper(90,30,0x42575e,0x293a44);scene.add(grid);grid.position.set(0,-.03,0);
const assembly=new THREE.Group();scene.add(assembly);let parts=[],selected=null,placing=null,groups=new Map(),nextId=1;const names={wall:'Armor wall',window:'Window wall',door:'Airlock door',corner:'Corner frame',solar:'Solar panel',utility:'Utility roof',antenna:'Antenna',hatch:'Service hatch',sign:'Info terminal',balcony:'Walkway',garden:'Bio planter',reactor:'Reactor',pillar:'Support pillar',vent:'Vent unit',brace:'Wall brace',floor:'Floor tile'};const icons=['▥','▣','▯','⌜','▱','⬡','♜','◉','⚑','╥','♧','◈','▮','▤','┐','▰'];
const mat=(color,metalness=.55)=>new THREE.MeshStandardMaterial({color,metalness,roughness:.65});let materials={};
function palette(){let color={olive:'#777969',slate:'#637485',sand:'#a09579'}[$('finish').value];materials={body:mat(color),frame:mat('#39454c'),edge:mat('#a6a89a'),dark:mat('#242f35'),solar:mat('#294970'),light:new THREE.MeshStandardMaterial({color:$('accent').value,emissive:$('accent').value,emissiveIntensity:1.4}),glass:new THREE.MeshStandardMaterial({color:'#315e66',metalness:.65,roughness:.2}),plant:mat('#619979',0)};}
function box(g,w,h,d,x,y,z,m='body'){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),materials[m]);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
function module(p){let g=new THREE.Group(),t=p.type;const b=(...args)=>box(g,...args);
if(['wall','window','door','corner'].includes(t)){
 b(3,2.8,.17,0,1.4,-1.42,'dark');b(2.65,2.45,.14,0,1.4,-1.3);for(let x of [-1.35,1.35]){b(.25,3,.38,x,1.5,-1.3,'frame');for(let y of [.22,2.8])b(.4,.32,.43,x,y,-1.3,'edge');}for(let y of [.25,2.72])b(2.65,.16,.26,0,y,-1.2,'edge');
 if(t==='window'){b(1.65,1.22,.22,0,1.6,-1.16,'frame');b(1.4,.98,.05,0,1.6,-1.03,'glass');b(1.14,.045,.06,0,1.98,-.99,'light');}
 if(t==='door'){b(1.62,2.3,.24,0,1.18,-1.12,'frame');b(1.26,2.12,.09,0,1.12,-.97,'dark');for(let x of [-.33,.33])b(.59,1.95,.09,x,1.08,-.9);b(.035,1.9,.06,0,1.08,-.83,'light');b(.5,.075,.09,0,2.26,-.98,'light');for(let x of [-1,1])b(.13,.34,.08,x,1,-1.02,'light');}
 if(t==='wall')for(let x of [-.75,.75]){b(.06,1.8,.06,x,1.4,-1.15,'frame');b(.5,.14,.09,x,.58,-1.12,'edge');}
 if(t==='corner')b(.3,2.8,2.9,-1.3,1.4,0,'frame');
}else if(t==='floor'){b(2.98,.14,2.98,0,.02,0,'frame');b(2.7,.05,2.7,0,.115,0);for(let x of [-1.1,1.1])b(.035,.02,2.5,x,.151,0,'edge');
}else if(t==='solar'||t==='utility'){let roof=new THREE.Group();g.add(roof);roof.rotation.x=-.28;b(2.7,.18,2.2,0,.42,0,'frame');if(t==='solar'){for(let x of [-.66,.66]){box(roof,1.2,.08,1.75,x,.7,0,'solar');for(let z of [-.65,-.32,0,.32,.65])box(roof,1.18,.012,.02,x,.751,z,'edge');for(let dx of [-.3,0,.3])box(roof,.012,.012,1.7,x+dx,.751,0,'edge');}}else{b(1.1,.85,1,0,.85,0);b(.65,.12,.5,0,1.3,0,'light');b(.3,.4,.12,.56,.9,0,'frame');}
}else if(t==='antenna'){b(1.7,.15,1.7,0,.12,0,'edge');const cone=new THREE.Mesh(new THREE.ConeGeometry(1.1,1.4,4),materials.body);cone.position.y=.9;cone.rotation.y=Math.PI/4;g.add(cone);b(.1,2.3,.1,0,1.8,0,'frame');b(.06,1.8,.06,.35,1.7,.2,'edge');b(.12,.14,.12,0,3,0,'light');
}else if(t==='balcony'){b(3,.18,2.3,0,1.65,0,'frame');for(let x of [-1.35,1.35]){b(.22,1.6,.25,x,.8,0);for(let z of [-1,1])b(.09,1,.09,x,2.2,z,'edge');}for(let z of [-1,1])b(2.9,.09,.09,0,2.7,z,'edge');
}else if(t==='garden'){b(2,.3,1,0,.2,0);b(1.8,.05,.8,0,.38,0,'dark');for(let x of [-.65,-.2,.25,.65]){b(.08,.7,.08,x,.7,0,'plant');b(.25,.12,.12,x+.08,.75,0,'plant');}b(2.1,1.6,.12,0,1.05,.4,'frame');b(1.85,1.4,.06,0,1.05,.32,'glass');
}else if(t==='sign'){b(.2,2.4,.2,0,1.2,0,'edge');b(1.15,.85,.15,.45,1.65,0,'frame');b(.94,.63,.03,.45,1.65,.09,'glass');b(.7,.055,.03,.45,1.78,.12,'light');b(.45,.03,.03,.33,1.56,.12,'light');b(.7,.12,.6,0,.08,0,'frame');
}else if(t==='reactor'){b(1.7,.35,1.3,0,.2,0);const dome=new THREE.Mesh(new THREE.SphereGeometry(.6,20,12,0,Math.PI*2,0,Math.PI/2),materials.glass);dome.position.y=.4;g.add(dome);b(.8,.05,.8,0,.45,0,'light');
}else if(t==='hatch'){b(1.8,2.6,.18,0,1.3,0,'frame');b(1.5,2.3,.12,0,1.3,.14);const ring=new THREE.Mesh(new THREE.TorusGeometry(.32,.07,8,24),materials.edge);ring.position.set(0,1.2,.3);g.add(ring);b(.6,.06,.06,0,2.2,.22,'light');
}else if(t==='brace'){b(.3,2.3,.5,0,1.15,0,'frame');b(1.6,.3,.5,.6,2.15,0);const diag=b(.17,1.6,.25,.5,1.65,0,'edge');diag.rotation.z=-.65;
}else{b(t==='pillar'?.7:1,2, t==='pillar'?.7:.9,0,1,0);b(1.1,.2,1.05,0,2.05,0,'frame');if(t==='vent')for(let y=.4;y<1.8;y+=.2)b(.75,.06,.07,0,y,.49,'dark');}
if(p.variant==='reinforced'){b(.15,2.8,.18,-1.05,1.4,-1);b(.15,2.8,.18,1.05,1.4,-1);}if(p.variant==='powered')b(.7,.06,.12,0,2.5,-1,'light');g.position.set(p.x*3,p.floor*3,p.z*3);g.rotation.y=p.rotation*Math.PI/2;g.userData.id=p.id;return g;}
function config(){return Object.fromEntries(['width','depth','levels','roof','preset','finish','accent'].map(k=>[k,['width','depth','levels'].includes(k)?Number($(k).value):$(k).value]));}
let outline;function rebuild(){palette();while(assembly.children.length){let g=assembly.children[0];g.traverse(o=>{if(o.geometry)o.geometry.dispose();});assembly.remove(g);}groups.clear();for(let p of parts){let g=module(p);assembly.add(g);groups.set(p.id,g);}highlight();$('parts').textContent=parts.length;$('count').textContent=`${parts.length} PARTS`;$('area').textContent=config().width*config().depth*9;for(let k of ['width','depth','levels'])$(k+'Value').textContent=$(k).value;localStorage.setItem('module-lab',JSON.stringify({version:1,config:config(),parts}));}
function highlight(){if(outline){scene.remove(outline);outline.geometry.dispose();outline.material.dispose();outline=null;}let p=parts.find(p=>p.id===selected);$('edit').hidden=!p;$('selectionHelp').hidden=!!p;$('selectedName').textContent=p?names[p.type]:'Nothing selected';if(p){outline=new THREE.BoxHelper(groups.get(p.id),0x69e8c3);scene.add(outline);$('floor').value=p.floor;$('angle').value=p.rotation;$('variant').value=p.variant;}}
function frame(){const bounds=new THREE.Box3().setFromObject(assembly);if(bounds.isEmpty()){controls.target.set(0,0,0);camera.position.set(15,15,15);return;}const center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(1.1,.95,1.3).multiplyScalar(Math.max(size.x,size.z,size.y,9)*1.3));controls.update();}
function generate(){parts=generateLayout(config());selected=null;nextId=parts.length+1;rebuild();frame();$('status').textContent='Building regenerated';}
for(let [i,t]of TYPES.entries()){let btn=document.createElement('button');btn.innerHTML=`<span>${icons[i]}</span>${names[t]}`;btn.dataset.type=t;btn.onclick=()=>{placing=t;document.querySelectorAll('#catalog button').forEach(b=>b.classList.toggle('active',b===btn));$('orbit').classList.remove('active');$('hint').textContent=`Click ground to place ${names[t]} · Escape to cancel`;};$('catalog').append(btn);}
function selectMode(){placing=null;document.querySelectorAll('#catalog button').forEach(b=>b.classList.remove('active'));$('orbit').classList.add('active');$('hint').textContent='Drag to orbit · Scroll to zoom · Click a module to select';}$('orbit').onclick=selectMode;
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;let rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);if(placing){let hit=ray.intersectObject(ground)[0];if(hit){let x=Math.round(hit.point.x/3),z=Math.round(hit.point.z/3),floor=0;if(parts.some(p=>p.type===placing&&p.x===x&&p.z===z&&p.floor===floor&&p.rotation===0)){$('status').textContent='That module already occupies this slot';return;}let p={id:`custom${nextId++}`,type:placing,x,z,floor,rotation:0,variant:'standard'};parts.push(p);selected=p.id;rebuild();$('status').textContent=`Placed ${names[p.type]}`;}}else{let hit=ray.intersectObjects(assembly.children,true)[0];let g=hit?.object;while(g&&!g.userData.id)g=g.parent;selected=g?.userData.id||null;highlight();}});
function edit(key,value){let p=parts.find(p=>p.id===selected);if(p){p[key]=value;rebuild();}}$('floor').onchange=()=>edit('floor',Math.max(0,Math.min(5,Number($('floor').value)||0)));$('angle').onchange=()=>edit('rotation',Number($('angle').value));$('variant').onchange=()=>edit('variant',$('variant').value);$('rotate').onclick=()=>{let p=parts.find(p=>p.id===selected);if(p)edit('rotation',(p.rotation+1)%4);};function remove(){parts=parts.filter(p=>p.id!==selected);selected=null;rebuild();}$('delete').onclick=remove;$('frame').onclick=frame;window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;if(e.key==='Escape')selectMode();if(e.key==='Delete')remove();if(e.key.toLowerCase()==='r')$('rotate').click();});
$('generate').onclick=generate;for(let k of ['width','depth','levels','roof'])$(k).oninput=generate;for(let k of ['finish','accent'])$(k).oninput=rebuild;$('grid').onchange=()=>grid.visible=$('grid').checked;$('preset').onchange=()=>{if($('preset').value==='station')$('roof').value='utility';generate();};$('reset').onclick=()=>{for(let [k,v]of Object.entries({width:4,depth:3,levels:1,roof:'solar',preset:'outpost',finish:'olive',accent:'#69e8c3'}))$(k).value=v;generate();};
$('save').onclick=()=>{let url=URL.createObjectURL(new Blob([JSON.stringify({version:1,config:config(),parts},null,2)],{type:'application/json'}));let a=document.createElement('a');a.href=url;a.download='modular-outpost.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('load').onclick=()=>$('file').click();function restore(v){if(!validProject(v))throw Error('Invalid project format');for(let[k,value]of Object.entries(v.config||{}))if(['width','depth','levels','roof','preset','finish','accent'].includes(k))$(k).value=value;parts=v.parts.map((p,i)=>({...p,id:`loaded${i}`}));nextId=parts.length+1;selected=null;rebuild();frame();}$('file').onchange=async()=>{try{restore(JSON.parse(await $('file').files[0].text()));$('status').textContent='Project imported';}catch{$('status').textContent='Could not import: invalid project JSON';}$('file').value='';};
try{let saved=JSON.parse(localStorage.getItem('module-lab'));if(saved)restore(saved);else generate();}catch{generate();}
new ResizeObserver(()=>{let w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe(viewport);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});
window.moduleLab={get parts(){return parts;},generate,scene,renderer};
